highlighter: pygments

exclude: ['README.md', 'Gemfile', 'notes.txt']

sass:
    sass_dir: _sass
    # Minification
#    style: compressed # for minification


# Site info
domain: www.quixotic-chris.com
title: Quixotic Chris
author: Chris Cooper
email: chris@quixotic-chris.com
description155: "This is the personal site of Chris Cooper, an aspiring computer scientist and soccer player who lives in Toronto."
main_square_image_url: /static/images/quixotic-chris.png

google_analytics:
    account: UA-47363412-1

google_plus:
    profile_url: "https://plus.google.com/115846485176399836261"

disqus:
    account: quixotic-chris

facebook:
    insights_id: unknown

